package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwandautils.QwandaMessage;
import org.json.JSONObject;

import life.genny.notifications.EmailHelper;
import life.genny.qwanda.message.QScheduleMessage;
import life.genny.notifications.SmsHelper;
import java.util.Arrays;
import java.time.ZoneOffset;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.KeycloakUtils;


rule "MEETING_REMINDER_EVENT"
	ruleflow-group 'Movement'
	salience 2
	no-loop
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		newApplication: BaseEntity()
		output : OutputParam( )
		controlSignalCode : String(controlSignalCode.equals("SCHEDULE_MEETING"))
	then
		System.out.println(drools.getRule().getName() + " : Rule fired" );
		System.out.println("Current Time is "+LocalDateTime.now());
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		
		newApplication = beUtils.getBaseEntityByCode(newApplication.getCode());
		
		String menteeBeCode = newApplication.getValue("PRI_MENTEE_CODE", null);
		
		String mentorBeCode = newApplication.getValue("PRI_MENTOR_CODE", null);
		
		System.out.println("################## START Shleemy ##################");
		
		
		
		
		
		
		retract(controlSignalCode);
		retract(newApplication);
	end
