package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.utils.TableUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.qwandautils.GennySettings;

rule "SET_PRI_STATUS_AS_MENTORING"
    ruleflow-group 'Movement'
    no-loop true
    salience 1
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity(code matches "APP_\\S+" )
		output : OutputParam()
		bucketCode : String(bucketCode.equals("MATCHED"))
		controlSignalCode : String(controlSignalCode.equals("MENTORING"))
     then
 		System.out.println("SET_PRI_STATUS_AS_MENTORING: Rule fired" );

		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

 		newApplication = beUtils.getBaseEntityByCode(newApplication.getCode());
 		Answer answer = new Answer(userToken.getUserCode(),newApplication.getCode(),"PRI_STATUS","MENTORING");
 		beUtils.saveAnswer(answer);


		System.out.println("SET_PRI_STATUS_AS_MENTORING: Answer = " + answer);
		System.out.println("SET_PRI_STATUS_AS_MENTORING: newApplication = " + newApplication);


		TableUtils.moveEntity(newApplication.getCode(), "SBE_MATCHED", "SBE_ROTARY_MENTORING", beUtils);
		
		String menteeBeCode = newApplication.getValue("PRI_MENTEE_CODE", null);
		String mentorBeCode = newApplication.getValue("PRI_MENTOR_CODE", null);
		
		System.out.println("^^^^^^^^^ menteeBeCode = " + menteeBeCode);
		System.out.println("^^^^^^^^^ mentorBeCode = " + mentorBeCode);
		
		BaseEntity menteeBe = beUtils.getBaseEntityByCode(menteeBeCode);
		if (menteeBe != null) {
			System.out.println("Sending email to mentee for created meeting request");
		}
		
		
		retract(newApplication)
		retract(bucketCode)
		retract(controlSignalCode)

end
