package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import java.util.UUID;
import life.genny.notifications.EmailHelper;
import java.util.Arrays;

import java.util.List;
import java.util.ArrayList;

rule "IS_MENTOR"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1000
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("MENTOR"))
		newBe : BaseEntity()

     then
 		System.out.println("IS_MENTOR: Rule fired" );
 		System.out.println("IS_MENTOR: newBe = " + newBe.getCode());

 	/*  Construct answer with Source, Target, Attribute Code, Value */
 		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_IS_MENTOR", "true"));
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_MENTOR_CODE", newBe.getCode()));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS", "OFF_SHORE"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_DISABLED", "false"));
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_TRAINING_STATUS", "INCOMPLETE"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_STATUS_COLOR", "#5cb85c"));
 		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"PRI_PROFILE", "COMPLETED"));

		String target = newBe.getCode();

		BaseEntity userBE = beUtils.getBaseEntityByCode(target);
		System.out.println("userBE = " +userBE);

		newBe = beUtils.getBaseEntityByCode(newBe.getCode());

		/* Set up in Keycloak */

		String randomPW = "VZQ564P828";
	    int targetLength = target.length();

	    System.out.println(target);
	    System.out.println(targetLength);

	    if (target.startsWith("PER_") && targetLength == 40) {
	      randomPW = target.substring(30,40);
	      System.out.println("Random Password used: " + randomPW);
	    } else {
	      System.out.println("Backup password used: " + randomPW);
	    }

		BaseEntity user = beUtils.getBaseEntityByCode(newBe.getCode());
		String userStr = newBe.getCode();
		String[] userSplit = userStr.split("_");
		String userCode = userSplit[1];
		System.out.println("User:: "+user+" with userCode:: "+userCode);

		String userId = "";
		String email = "";

		String firstname = user.getValue("PRI_FIRSTNAME",null);
		if (firstname != null) {
			String lastname = user.getValue("PRI_LASTNAME",null);
			if (lastname != null) {
				email = user.getValue("PRI_EMAIL",null);
				if (email != null) {
					/*String userPassword = UUID.randomUUID().toString().substring(0,10);*/
					/* TODO HACK */
					if (true) {
						String userPassword = "password1";
						userId = KeycloakUtils.updateUser(userCode,serviceToken.getToken(), serviceToken.getRealm(), email, firstname, lastname,  email, userPassword,"user", "users");
						userId = userId.toUpperCase();
						Answer keycloakId = new Answer(beUtils.getGennyToken().getUserCode(),newBe.getCode(),"PRI_UUID",userId);
						beUtils.saveAnswer(keycloakId);
						System.out.println("Created User "+email+" in Keycloak with id = "+userId + " and password:" +userPassword);
					} else {
					     System.out.println("KEYCLOAK USER CREATION DISABLED IN RULE IS_MENTOR");
					}
				}
			}
		}



		String endPoint = GennySettings.projectUrl + "/v7/notes";

		String tag = "ni";

		QwandaUtils.apiPostNote(endPoint, userToken.getUserCode(), tag, userToken.getUserCode(), "Added a Mentor: " + firstname, serviceToken.getToken());

		System.out.println("I just posted the note");
		System.out.println("Note endPoint: " +endPoint);
		System.out.println("Note userToken.getUserCode(): " +userToken.getUserCode());

		BaseEntity mentorBe = beUtils.getBaseEntityByCode(newBe.getCode());

		if(mentorBe != null){

			QDataBaseEntityMessage mentorBeMsg = new QDataBaseEntityMessage(mentorBe);
			mentorBeMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", JsonUtils.toJson(mentorBeMsg));
		}

		/* Send email to Mentee */
		/*

		String rawSendEmail = user.getValue("LNK_SEND_EMAIL", null);
		System.out.println("rawSendEmail: " + rawSendEmail + " Sending email to: " + email);

		if (rawSendEmail.equals("SEL_YES")) {

			BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());

			String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, email, serviceToken.getToken());
			System.out.println("token: " + token);

			String url = GennySettings.projectUrl+"/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX0ZJTklTSF9JTlRFUk4=";
			System.out.println("url: " + url);

			url = url + "?token=" + token;
			System.out.println("url: " + url);

			String subject = "You have been registered on MentorMatch";
			String template_id = "d-0f954dec3a8642c8bcb21b1c8344b925";

			System.out.println("email: " + email);
			System.out.println("subject: " + subject);
			System.out.println("template_id: " + template_id);
			System.out.println("randomPW: " + randomPW);


			HashMap<String, String> templateData = new HashMap<String, String>();
			templateData.put("Mentee", firstname);
			templateData.put("pw", randomPW);
			templateData.put("url", url);

			List<String> bccList = Arrays.asList("rahul@gada.io");

			/* if (!GennySettings.projectUrl.contains("dev")) {
			if (true) {
				EmailHelper.sendGrid(beUtils, email, null, bccList, subject, template_id, templateData);
				System.out.println("Sent Email to " + email);
				System.out.println("bccList:: " + bccList);
			} else {
				System.out.println("WARNING: Email not sent because on Dev server");
			}

		} else {
			System.out.println("rawSendEmail is not sent: " + rawSendEmail);
		} */


		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */

		retract(newBe)

end
