package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_PEER_MENTORING"
	ruleflow-group 'GenerateSearches'
	no-loop true
	when
		not SearchEntity (code == "SBE_PEER_MENTORING")
		serviceToken : GennyToken( code == "PER_SERVICE")
	then
		System.out.println("   Generate "+drools.getRule().getName() );

		SearchEntity searchBE = new SearchEntity("SBE_PEER_MENTORING", "Peer Mentoring")
						/* Sorts */
						.addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)

						/* Filters */
						.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
						.addFilter("PRI_STATUS", SearchEntity.StringFilter.LIKE, "MENTORING")
						.addFilter("PRI_DISABLED", false)

						/* Columns */
						.addColumn("PRI_NAME", "Name")

						/* Display Code */
						.setDisplayMode("CARD:MAIN_2")

						/* Actions */
						.addAction("PRI_EVENT_VIEW", "View Profile")
						.setPageStart(0).setPageSize(15);

		searchBE.setRealm(serviceToken.getRealm());

		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
