package life.genny.rules;

import java.io.IOException;

global life.genny.qwanda.message.QBulkMessage payload;
	
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.qwanda.Answer;
import java.util.List;
import java.util.ArrayList;
import life.genny.model.OutputParamTreeSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.utils.TableUtils;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import org.drools.core.spi.KnowledgeHelper;

rule "SEND_QUICK_ADD_ITEMS_MENTEE"
	ruleflow-group 'SendAsks'
	salience 9
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		allowed : Allowed(code == "MENTEE")
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName() + " triggered");

		/* get the addItems ask from cache */
		Ask quickAddItemsAsk = VertxUtils.getObject(serviceToken.getRealm(), "", "QUICK_ADD_ITEMS_MENTEE", Ask.class, serviceToken.getToken());

		if(quickAddItemsAsk == null){
			System.out.println("quickAddItemsAsk is not in cache");

		}else{

			String json = JsonUtils.toJson(quickAddItemsAsk);
			json = json.replaceAll("PER_SERVICE", userToken.getUserCode());

			quickAddItemsAsk = JsonUtils.fromJson(json, Ask.class);
			/* send the addItems asks */
			QDataAskMessage askMsg = new QDataAskMessage(quickAddItemsAsk);
			askMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", askMsg);
		}


end
