package life.genny.rules;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QScheduleMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QScheduleMessage;
import life.genny.utils.BucketUtils;
import life.genny.utils.TableUtils;
import life.genny.utils.ShleemyUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.qwandautils.GennySettings;
import life.genny.notifications.EmailHelper;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

rule "REMIND_TO_AGREE_FOR_MENTORING"
    ruleflow-group 'EventProcessing'
    no-loop true
    salience 5
    when
   		$message : QEventMessage(data.code == "SCHEDULE_AGREE_TO_MENTORING_EMAIL")
   		userToken : GennyToken  ()
		serviceToken : GennyToken (code == "PER_SERVICE" )
		beUtils : BaseEntityUtils ()
     then
 		System.out.println(drools.getRule().getName() + " : Rule fired" );
 		System.out.println("Current Time is "+LocalDateTime.now());
		String targetCode = $message.getData().getTargetCode();
		System.out.println("targetCode: " +targetCode);	
		
		BaseEntity newApplication = beUtils.getBaseEntityByCode(targetCode);
		String menteeBeCode = newApplication.getValue("PRI_MENTEE_CODE", null);
		String mentorBeCode = newApplication.getValue("PRI_MENTOR_CODE", null);
		
		BaseEntity menteeBe = beUtils.getBaseEntityByCode(menteeBeCode);
		BaseEntity mentorBe = beUtils.getBaseEntityByCode(mentorBeCode);
		
		System.out.println("^^^^^^^^^ menteeBeCode = " + menteeBeCode);
		System.out.println("^^^^^^^^^ mentorBeCode = " + mentorBeCode);
		
		BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());

		if (mentorBe != null) {
			System.out.println("#### Sending email to agree to mentoring ####");

			/* SEND EMAIL */
                String mentorEmail = mentorBe.getValue("PRI_EMAIL", null);
				System.out.println("mentorEmail: " + mentorEmail);

				String mentorName = mentorBe.getValue("PRI_NAME", null);
				System.out.println("mentorName: " + mentorName);

				if (mentorEmail != null) {

						String subject = "Confirm to Mentoring";
						String template_id = "d-a3e6ed8e5d3041eaad1d26836b649f54";
						
						String urlParentCode = "QUE_FAKE_PARENT";
                		String urlCode = "ACT_MENTOR_MENTORING_AGREE";

					 	String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, mentorEmail, serviceToken.getToken());
       					System.out.println("token: " + token);
       					
                		/* Encode each section of the url */
                		urlParentCode = new String(Base64.getEncoder().encode(urlParentCode.getBytes()));
                		urlCode = new String(Base64.getEncoder().encode(urlCode.getBytes()));
            
                		String url = GennySettings.projectUrl+"/home/"+urlParentCode+"/"+urlCode;
                		
                		url = url + "?token=" + token;
                		System.out.println("url: " + url);

						HashMap<String, String> templateData = new HashMap<String, String>();

                        templateData.put("Mentor", mentorName);
                        templateData.put("url", url);

                        System.out.println("-------- EMAIL DATA --------");
                        System.out.println("subject: " +subject);
						System.out.println("template_id: " +template_id);
						System.out.println("email: " + mentorEmail);
						System.out.println("Mentor: " +mentorName);
						System.out.println("----------------------------");

						if (!GennySettings.projectUrl.contains("dev")) {

								List<String> bccList = Arrays.asList("tarjnee.gandhi@outcomelife.com.au");
								EmailHelper.sendGrid(beUtils, mentorEmail, null, bccList, subject, template_id, templateData, true);

								System.out.println("Email Sent ||| Subject: " + subject + "||| template_id: " + template_id);

						} else {
								List<String> bccList = Arrays.asList("tarjnee.gandhi@outcomelife.com.au");
								EmailHelper.sendGrid(beUtils, mentorEmail, null, bccList, subject, template_id, templateData, true);

								System.out.println("Email Sent ||| Subject: " + subject + "||| template_id: " + template_id);

							System.out.println("WARNING: Email not sent because on Dev server");
						}
				} else {
					System.out.println("ERROR Null Mentor email");
				}
		}
		retract($message)
end
