package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.utils.TableUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.qwandautils.GennySettings;
import life.genny.notifications.EmailHelper;
import java.util.HashMap;
import java.time.LocalDateTime;

rule "MEETING_REQUEST_NOTIFICATION"
    ruleflow-group 'Movement'
    no-loop true
    salience 1
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity(code matches "APP_\\S+" )
		output : OutputParam()
		bucketCode : String(bucketCode.equals("MATCHED"))
		controlSignalCode : String(controlSignalCode.equals("MEETING_REQUEST_NOTIFICATION"))
		beUtils : BaseEntityUtils()
     then
 		System.out.println("MEETING_REQUEST_NOTIFICATION: Rule fired" );

 		newApplication = beUtils.getBaseEntityByCode(newApplication.getCode());

		System.out.println("SET_PRI_STATUS_AS_MENTORING: newApplication = " + newApplication);

		String menteeBeCode = newApplication.getValue("PRI_MENTEE_CODE", null);
		String mentorBeCode = newApplication.getValue("PRI_MENTOR_CODE", null);
		
		LocalDateTime meetingTime = newApplication.getValue("PRI_MEETING_START_DATETIME", null);
		
		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("hh:mm:ss a, E, dd MMM yyyy");
		String meetingTimeStr = dtf.format(meetingTime);
		
		String meetingType = newApplication.getValue("LNK_MEETING_TYPE", null);
		
		System.out.println("^^^^^^^^^ menteeBeCode = " + menteeBeCode);
		System.out.println("^^^^^^^^^ mentorBeCode = " + mentorBeCode);
		System.out.println("^^^^^^^^^ meetingTimeStr = " + meetingTimeStr);
		System.out.println("^^^^^^^^^ meetingType = " + meetingType);

		BaseEntity menteeBe = beUtils.getBaseEntityByCode(menteeBeCode);
		BaseEntity mentorBe = beUtils.getBaseEntityByCode(mentorBeCode);
		if (menteeBe != null) {
			System.out.println("Sending email to mentee for created meeting request");

			/* SEND EMAIL */
                String menteeEmail = menteeBe.getValue("PRI_EMAIL", null);
				String menteeName = menteeBe.getValue("PRI_NAME", null);
				if (menteeEmail != null) {

						String subject = "Dates and times of your upcoming MentorMatch mentoring sessions";
						String template_id = "d-3d5a56f4c7a9449690898696c4e46fa9";

					    HashMap<String, String> templateData = new HashMap<>();

                        templateData.put("Mentee", menteeName);
                        templateData.put("MeetingTime", meetingTimeStr);

                        System.out.println("-------- EMAIL DATA --------");
                        System.out.println("subject: " +subject);
						System.out.println("template_id: " +template_id);
						System.out.println("email: " + menteeEmail);
						System.out.println("Mentee: " +menteeName);
						System.out.println("----------------------------");

						if (!GennySettings.projectUrl.contains("dev")) {

								List<String> bccList = Arrays.asList("internmatch@outcomelife.com.au");
								EmailHelper.sendGrid(beUtils, menteeEmail, null, bccList, subject, template_id, templateData, true);
								System.out.println("Email Sent ||| email: "+ menteeEmail + " ||| Subject: " + subject + "||| template_id: " + template_id);

						} else {
								List<String> bccList = Arrays.asList("internmatch@outcomelife.com.au");
								menteeEmail = "tarjnee.gandhi@outcomelife.com.au";
								EmailHelper.sendGrid(beUtils, menteeEmail, null, bccList, subject, template_id, templateData, true);
								System.out.println("Email Sent ||| email: "+ menteeEmail + " ||| Subject: " + subject + "||| template_id: " + template_id);

							System.out.println("WARNING: Email not sent because on Dev server");
						}
				} else {
					System.out.println("ERROR Null Mentee email");
				}
			}
			/* Email to mentor created meeting request*/

		if (mentorBe != null) {
			System.out.println("Sending email to mentor for meeting request");

			/* SEND EMAIL */
                String mentorEmail = mentorBe.getValue("PRI_EMAIL", null);
				System.out.println("mentorEmail: " + mentorEmail);

				String mentorName = mentorBe.getValue("PRI_NAME", null);
				System.out.println("mentorName: " + mentorName);

				if (mentorEmail != null) {

						String subject = "Dates and times of your upcoming MentorMatch mentoring sessions – please confirm!";
						String template_id = "d-8df9d4b9362e4b38a0cd2f0de576ac48";
						
						String urlParentCode = "QUE_FAKE_PARENT";
                		String urlCode = "ACT_MENTOR_MEETING_AGREE";

                		/* Encode each section of the url */
                		urlParentCode = new String(Base64.getEncoder().encode(urlParentCode.getBytes()));
                		urlCode = new String(Base64.getEncoder().encode(urlCode.getBytes()));
            
                		String url = GennySettings.projectUrl+"/home/"+urlParentCode+"/"+urlCode;
                		System.out.println("url: " + url);

						HashMap<String, String> templateData = new HashMap<String, String>();

                        templateData.put("Mentor", mentorName);
                        templateData.put("MeetingTime", meetingTimeStr);
                        templateData.put("url", url);

                        System.out.println("-------- EMAIL DATA --------");
                        System.out.println("subject: " +subject);
						System.out.println("template_id: " +template_id);
						System.out.println("email: " + mentorEmail);
						System.out.println("Mentor: " +mentorName);
						System.out.println("url: " + url);
						System.out.println("----------------------------");

						if (!GennySettings.projectUrl.contains("dev")) {

								List<String> bccList = Arrays.asList("internmatch@outcomelife.com.au");
								EmailHelper.sendGrid(beUtils, mentorEmail, null, bccList, subject, template_id, templateData, true);

								System.out.println("Email Sent ||| email: "+ mentorEmail + " ||| Subject: " + subject + "||| template_id: " + template_id);

						} else {
								List<String> bccList = Arrays.asList("internmatch@outcomelife.com.au");
								mentorEmail = "tarjnee.gandhi@outcomelife.com.au";
								EmailHelper.sendGrid(beUtils, mentorEmail, null, bccList, subject, template_id, templateData, true);

								System.out.println("Email Sent ||| email: "+ mentorEmail + " ||| Subject: " + subject + "||| template_id: " + template_id);

							System.out.println("WARNING: Email not sent because on Dev server");
						}
				} else {
					System.out.println("ERROR Null Mentor email");
				}
		}

		retract(newApplication)
		retract(bucketCode)
		retract(controlSignalCode)

end
