package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.List;
import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.utils.TableUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.qwandautils.GennySettings;
import life.genny.notifications.EmailHelper;

rule "CREATE_MENTEE_MENTOR_APP"
    ruleflow-group 'Movement'
    no-loop true
    salience 1
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity( code matches "APP_\\S+" )
		output : OutputParam()
		bucketCode : String(bucketCode.equals("TRAINING"))
		controlSignalCode : String(controlSignalCode.equals("MATCH"))
		associatedMenteeBe : BaseEntity( code matches "PER_\\S+" )

     then
 		System.out.println("CREATE_MENTEE_MENTOR_APP: Rule fired" );

		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		/* Refresh the BaseEntity because mysterious reasons told to me by Chris... */
 		newApplication = beUtils.getBaseEntityByCode(newApplication.getCode());
 		associatedMenteeBe = beUtils.getBaseEntityByCode(associatedMenteeBe.getCode());

		/*Answer answer = new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_STATUS", "MATCHED");
		beUtils.saveAnswer(answer);
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_DISABLED", "false"));*/

		/*System.out.println("SET_PRI_STATUS_AS_MATCHED: Answer = " + answer);*/
		System.out.println("SET_PRI_STATUS_AS_MATCHED: newApplication = " + newApplication);

		/* Save status to the PER */
		String appMentee = associatedMenteeBe.getCode();
		System.out.println("appMentee = " + appMentee);

		if (appMentee != null) {
 				beUtils.saveAnswer(new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_MENTEE_CODE", appMentee));
		} else {
			System.out.println("ERROR: Null appMentee");
		}

		/* Getting Mentor & Mentee values */

		String mentorPer = beUtils.quantumStrip(newApplication, "LNK_SELECT_MENTOR", "mentorPer");
		BaseEntity assocMentorPer = beUtils.quantumBe(mentorPer, "assocMentorPer");
		System.out.println("assocMentorPer: " +assocMentorPer);

		if (mentorPer != null) {
 				beUtils.saveAnswer(new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_MENTOR_CODE", mentorPer));
		} else {
			System.out.println("ERROR: Null mentorPer");
		}

		String assocMentee = newApplication.getValue("PRI_MENTEE_CODE", null);
		System.out.println("assocMentee: " +assocMentee);

		if (associatedMenteeBe != null && assocMentorPer != null) {

			String firstname = associatedMenteeBe.getValue("PRI_FIRSTNAME", null);
 			String lastname = associatedMenteeBe.getValue("PRI_LASTNAME", null);
 			String name = "";

			System.out.println("firstname = " +firstname);
			System.out.println("lastname = " +lastname);

			if (firstname != null) {
				if (lastname != null) {
						name = firstname + " " + lastname;
						System.out.println("name = " +name);

						if (name != null) {

								Answer answer = new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_MENTEE_NAME", name);
								beUtils.saveAnswer(answer);
		                        beUtils.saveAnswer(new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_NAME", name));

								/*answer = new Answer(userToken.getUserCode(), newApplication.getCode(), "PRI_NAME", name);
								beUtils.saveAnswer(answer);*/
						} else {
							System.out.println("ERROR: Null name");
						}
				} else {
					System.out.println("ERROR: Null lastname");
				}
			} else {
				System.out.println("ERROR: Null firstname");
			}

			/* Saving APP code in PER Mentor */
			if (newApplication.getCode() != null) {
				beUtils.saveAnswer(new Answer(userToken.getUserCode(), assocMentorPer.getCode(), "PRI_APP_LNK_CODE", newApplication.getCode()));

				String assocAppMentor = assocMentorPer.getValue("PRI_APP_LNK_CODE", null);
				System.out.println("assocAppMentor: " + assocAppMentor);
			}

            /* Send Invite Email to Mentor */
            String mentorEmail = assocMentorPer.getValue("PRI_EMAIL", null);

            if (mentorEmail != null) {
                System.out.println("Sending invite to " + mentorEmail);

                BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());

                String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, mentorEmail, serviceToken.getToken());
                System.out.println("token: " + token);

                String url = GennySettings.projectUrl+"/home/UVVFX0ZBS0VfUEFSRU5U/UVVFX01FTlRPUl9BR1JFRV9UT19NRU5UT1JfR1JQ";
                System.out.println("url: " + url);

                url = url + "?token=" + token;
                System.out.println("url: " + url);

                String subject = "You have been registered on MentorMatch";
                String template_id = "d-0f954dec3a8642c8bcb21b1c8344b925";

                System.out.println("email: " + mentorEmail);
                System.out.println("subject: " + subject);
                System.out.println("template_id: " + template_id);
                /*System.out.println("randomPW: " + randomPW);*/


                HashMap<String, String> templateData = new HashMap<String, String>();
                templateData.put("Mentee", firstname);
                /*templateData.put("pw", randomPW);*/
                templateData.put("url", url);

                List<String> bccList = Arrays.asList("rahul@gada.io");

                    if (true) {

                    EmailHelper.sendGrid(beUtils, mentorEmail, null, bccList, subject, template_id, templateData, true);
                    System.out.println("Sent Email to " + mentorEmail);
                    System.out.println("bccList:: " + bccList);

                    } else {
                    System.out.println("WARNING: Email not sent because on Dev server");
                }

            } else {
                System.out.println("ERROR: Null mentorEmail");
            }

        }

end