package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.utils.TableUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.qwandautils.GennySettings;
import life.genny.notifications.EmailHelper;
import java.util.HashMap;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

rule "SEND_EMAIL_TO_SCHEDULE_MEETING"
    ruleflow-group 'Notification'
    no-loop true
    salience 1
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity(code matches "APP_\\S+" )
		output : OutputParam()
		controlSignalCode : String(controlSignalCode.equals("SCHEDULE_MEETING_EMAIL"))
		beUtils : BaseEntityUtils()
     then
 		System.out.println(drools.getRule().getName() + " : Rule fired" );
 		System.out.println("Current Time is "+LocalDateTime.now());
 		
 		newApplication = beUtils.getBaseEntityByCode(newApplication.getCode());

		System.out.println(drools.getRule().getName() + " :: newApplication = " + newApplication);
		
		
		String menteeCode = newApplication.getValue("PRI_MENTEE_CODE", null);
		String mentorCode = newApplication.getValue("PRI_MENTOR_CODE", null);
 		
 		BaseEntity menteeBe = beUtils.getBaseEntityByCode(menteeCode);
		BaseEntity mentorBe = beUtils.getBaseEntityByCode(mentorCode);
		
		/* Saving APP code in PER Mentor */
			if (newApplication.getCode() != null) {
				beUtils.saveAnswer(new Answer(userToken.getUserCode(), menteeBe.getCode(), "PRI_APP_LNK_CODE", newApplication.getCode()));

				String assocAppMentee = beUtils.quantumStrip(menteeBe, "PRI_APP_LNK_CODE", "assocAppMentor");
				System.out.println("assocAppMentee: " + assocAppMentee);
			}
		
		
		BaseEntity project = beUtils.getBaseEntityByCode("PRJ_"+ serviceToken.getRealm().toUpperCase());

		if (menteeBe != null) {
			System.out.println("#### Sending email to mentee to confirm meeting timings ####");

			/* SEND EMAIL */
                String menteeEmail = menteeBe.getValue("PRI_EMAIL", null);
				System.out.println(drools.getRule().getName() + " :: menteeEmail: " + menteeEmail);

				String menteeName = menteeBe.getValue("PRI_NAME", null);
				System.out.println(drools.getRule().getName() + " :: menteeName: " + menteeName);

				if (menteeEmail != null) {

						String subject = "Your mentor provided availability.";
						String template_id = "d-3d5a56f4c7a9449690898696c4e46fa9";
						
						String urlParentCode = "QUE_FAKE_PARENT";
                		String urlCode = "ACT_CONFIRM_MEETING";

					 	String token = KeycloakUtils.getImpersonatedToken(serviceToken.getKeycloakUrl(), serviceToken.getRealm(), project, menteeEmail, serviceToken.getToken());
       					System.out.println("token: " + token);
       					
                		/* Encode each section of the url */
                		urlParentCode = new String(Base64.getEncoder().encode(urlParentCode.getBytes()));
                		urlCode = new String(Base64.getEncoder().encode(urlCode.getBytes()));
            
                		String url = GennySettings.projectUrl+"/home/"+urlParentCode+"/"+urlCode;
                		
                		url = url + "?token=" + token;
                		System.out.println("url: " + url);
                		
                		LocalDateTime primaryAvl = newApplication.getValue("PRI_PRIMARY_AVAILABILITY", null);
                		LocalDateTime secondAvl = newApplication.getValue("PRI_SECONDARY_AVAILABILITY", null);
                		LocalDateTime tertiaryAvl = newApplication.getValue("PRI_TERTIARY_AVAILABILITY", null);
                		String meetingDuration = newApplication.getValue("LNK_MEETING_DURATION", null);
                		String agenda = newApplication.getValue("PRI_MEETING_AGENDA", null);
                		String note = newApplication.getValue("PRI_MEETING_NOTE", null);
                		
                		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("hh:mm:ss a, E, dd MMM yyyy");
						String primaryAvlStr = dtf.format(primaryAvl);
						String secondAvlStr = dtf.format(secondAvl);
						String tertiaryAvlStr = dtf.format(tertiaryAvl);

						HashMap<String, String> templateData = new HashMap<String, String>();

                        templateData.put("Mentee", menteeName);
                        templateData.put("availability1", primaryAvlStr);
                        templateData.put("availability2", secondAvlStr);
                        templateData.put("availability3", tertiaryAvlStr);
                        templateData.put("duration", meetinDuration);
                        templateData.put("agenda", agenda);
                        templateData.put("note", note);
                        templateData.put("url", url);

                        System.out.println("-------- EMAIL DATA --------");
                        System.out.println("subject: " +subject);
						System.out.println("template_id: " +template_id);
						System.out.println("email: " + menteeEmail);
						System.out.println("Mentee: " +menteeName);
						System.out.println("----------------------------");

						if (!GennySettings.projectUrl.contains("dev")) {

								List<String> bccList = Arrays.asList("tarjnee.gandhi@outcomelife.com.au");
								EmailHelper.sendGrid(beUtils, menteeEmail, null, bccList, subject, template_id, templateData, true);

								System.out.println("Email Sent ||| Subject: " + subject + "||| template_id: " + template_id);

						} else {
								List<String> bccList = Arrays.asList("tarjnee.gandhi@outcomelife.com.au");
								EmailHelper.sendGrid(beUtils, menteeEmail, null, bccList, subject, template_id, templateData, true);

								System.out.println("Email Sent To ||| " + menteeEmail + " Subject: " + subject + "||| template_id: " + template_id);

							System.out.println("WARNING: Email not sent because on Dev server");
						}
				} else {
					System.out.println("ERROR Null Mentee email");
				}
		}
		retract(newApplication)
		retract(controlSignalCode)

end
